# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Blank', max_length=128)),
                ('principle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=3, default=0.05, max_digits=5)),
                ('compoundings', models.IntegerField(default=1)),
                ('year', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Run'),
        ),
    ]
