# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_growth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='Blank', max_length=128),
        ),
    ]
