# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_growth', '0002_auto_20160615_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c_growth.Array')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Array')),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, default=0.05, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(default='Blank', max_length=128),
        ),
        migrations.AlterField(
            model_name='data',
            name='principle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Principle'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Rate'),
        ),
        migrations.AlterField(
            model_name='run',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
