# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_growth', '0003_auto_20160616_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compounding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='array',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='element',
            name='array',
        ),
        migrations.AlterField(
            model_name='data',
            name='compoundings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Compounding'),
        ),
        migrations.AlterField(
            model_name='data',
            name='interest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Gains'),
        ),
        migrations.AlterField(
            model_name='data',
            name='total',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Sum'),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='c_growth.Time'),
        ),
        migrations.DeleteModel(
            name='Array',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
